% test_all_graph

list = {...
'cbar test', ...
'im test', ...
'im_toggle test', ...
'jf_add_slider test', ...
'jf_mip3 test', ...
'jf_slicer test', ...
'montager test', ...
'plot_cell test', ...
'plot_ellipse test', ...
'slicer3 test', ...
'subplot_stack test', ...
'texts test', ...
'xtick test', ...
};

%'movie2 test', ...
%'savefig test', ...

run_mfile_local(list)
